name: lab_gui_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  side_sheet_material3: ^0.0.1
  http: ^0.13.6
  get_storage: ^2.1.1
  async: ^2.11.0
  syncfusion_flutter_datagrid: ^21.2.4
  flutter_fancy_tree_view: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
