name: lab_gui_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  side_sheet_material3: ^0.0.1
  http: ^1.1.0
  get_storage: ^2.1.1
  async: ^2.11.0
  syncfusion_flutter_datagrid: ^27.2.4
  syncfusion_flutter_core: ^27.2.4
  flutter_fancy_tree_view: ^1.1.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  osm_nominatim: ^3.0.0
  context_menus: ^2.0.0+1
  responsive_grid: ^2.3.0
  syncfusion_localizations: ^27.2.4
  shared_preferences: ^2.1.2
  dropdown_button2: ^2.1.2
  syncfusion_flutter_datagrid_export: ^27.2.4
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
